---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - loki.yaml
  - secrets/influxdb2-auth.yaml
  - influxdb2.yaml
  - telegraf.yaml
  - promtail.yaml

