---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 1m
  chart:
    spec:
      chart: kyverno
      version: "2.5.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: default
      interval: 1m
  values:
    replicaCount: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  interval: 1m
  chart:
    spec:
      chart: kyverno-policies
      version: "2.5.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: default
      interval: 1m

