---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: https-credentials
  url: https://github.com/notapipeline/cluster-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nebula
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: cluster-apps
  path: "./clusters/nebula"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops
  postBuild:
    substitute:
      domain: choclab.net
      organisation: choclab
      cluster: choclab
      bucket: nebula
      database: nebula
      region: eu-central-1
      cidr1: 10.0.0.0/16
      nfsServer: nebula
      nfsPath: /cluster/fs
