---
# Crossplane helm repository
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 1m
  url: https://charts.crossplane.io/stable

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: crossplane
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: crossplane-system
  values:
    metrics:
      enabled: true

  targetNamespace: crossplane-system
  install:
    remediation:
      retries: 3
      remediateLastFailure: false
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: false
