---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-composites
  namespace: crossplane-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: cluster-apps
    namespace: flux-system
  path: "./clusters/nebula/namespaces/crossplane-system/crossplane/composites"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: crossplane-sops
  postBuild:
    substitute:
      domain: ${domain}
      organisation: ${organisation}
      cluster: ${cluster}
      region: ${region}
  dependsOn:
  - name: crossplane-components