---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: frontend
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "6.32.7"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
      interval: 1m
  values:
    admin:
      existingSecret: grafana-admin
      passwordKey: password
      userKey: username
    autoscaling:
      enabled: true
      maxReplicas: 3
      metrics:
      - resource:
          name: cpu
          targetAverageUtilization: 60
        type: Resource
      - resource:
          name: memory
          targetAverageUtilization: 60
        type: Resource
      minReplicas: 1
    envFromSecret: grafana-db
    grafana.ini:
      analytics:
        check_for_updates: true
      database:
        host: nebula.choclab.net:3306
        name: grafana
        type: mysql
      grafana_net:
        url: https://grafana.net
      log:
        mode: console
      paths:
        data: /var/lib/grafana/
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
    ingress:
      enabled: true
      hosts:
      - grafana.choclab.net
      ingressClassName: nginx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
