apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: crossplane-test-sg
spec:
  forProvider:
    region: ${region}
    vpcIdRef:
      name: test-vpc
    groupName: crossplane-test-sg
    description: Cluster communication with worker nodes
    tags:
    - key: testing
      value: tags can be created
    - key: andmultilple
      value: work as anticipated
  providerConfigRef:
    name: choclab-aws-provider
