---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane
resources:
  - namespace.yaml
  - secrets/choclab-aws-credentials.yaml
  - crossplane.yaml
  - provider.yaml
  - aws
