apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:ZkJfLwZ4s4FWsJslDvSMpG7dptdtUDHoTN3GGtjuuAtIT+1I9h58EGQ87EY=,iv:zvV3ImN0MVfhhFIQKxT180PMNY5UAbA9UhNYUD8Iryg=,tag:rcui1wWqFqN0BDtBxyww5g==,type:str]
    admin-token: ENC[AES256_GCM,data:4NsqXwQvOnxZnyXzgkiwyAFOMb+iA6laLzYd773sP8TlVyZFF6bKXLkY0VA=,iv:7IHiwVwjB/1iaIzZkjoTBdiysoDuD+h2uhwWgrY6gww=,tag:xkvCR/7W93ksmREoY9xDlA==,type:str]
kind: Secret
metadata:
    name: influxdb2-auth
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-07T06:21:30Z"
    mac: ENC[AES256_GCM,data:15WMZCuolcTpvKbuoV50zdVYetj+tO8i4rsaBVZtMas45d8NPgP6ov+FkGyHPRZggByyE0TfZxtMYFnspeNmnekP2+8AyHRRDQOssFjQ1oP0MX2xmx+YycpBGz/WeFACJ7eng5DNmqysPHtuLoCIut+t+ZEpuzVb+D9EHp922gk=,iv:DGU2Y1ox1DwYzVLguJHCLO66YNOdJDSJPC8UKmmPxC0=,tag:yufDn2llEYsk7+WfafuKQg==,type:str]
    pgp:
        - created_at: "2022-08-07T06:21:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyC81PBBqFTyAQ//RvqOGeYXDAQie2lrAnHJYq7g15+oz8HT32kiPwnm6yoj
            Tp+M7BnVWcXFj5CLnjPNF/FTclAD2C1Kbyka3wuJsMHD96sMMs+SUPHqe4HlcVA5
            QpHRGfNIw51BFxVIIaQ/4Q4YMfkoLCAZQNGjQTUQYgjMOm5n/TEuM/aTR+/GCTQy
            YGigwwfMfmT+T0vlpAVerD9N3L7a51oxsg3KeUo7cpuRCmo7JoF7ZjGCRo+pcuZr
            Xq4sZi04KNdy7K3XKIWj6lVt1Nv19lm9Hgs6ZS2TShgxspU3TXFlaYFPU9AyMiaM
            SzBEmvY4k+ChqvkVLbZB7ccU7LLlfFlLYVTCPhE0f8IuRzLeZU8ZLH4d3JCCcaHv
            wsx+BeCZHU7T3J8J/sTn+JibMRA2WgFsBzpOWFWo3H0f81BdcIEjJAGvSQP+LbzY
            eHq2mZLxuxNBmCn9LJlugQf5dmqRL3esY6idZTq7dG2X+EZOydRhwhQla0b8RUfJ
            0q5hZ+IbEnI0mP3pijQ9kEB3sU3DqQS9nuHzWAx17Zhdlcf09pXISw4PL9ExmqfQ
            lHPxezzTH4D+k4qk1bwnrdMdZZ/DwTACM5EZdRhnkbvWo32GZBhzk4EL2o+B3LdO
            /B+v4WAlY/IUGdAQzB+sN4VFyAAQ+tLDumrEOxThaw+rIMdyNmH1GkNyRX0RrDrS
            XgFYaFWcxSdu2NqQfQ2e6eiBbiDJcZ8tE/JNSvsgzRPEJeSq8CR4gdlaLyVd6lI4
            qLqlS26f+DQFAaKFJ7s8X4svXtozsPhT+oMeh6zhXRkdI8us/aZ207V033YqHxg=
            =4T3S
            -----END PGP MESSAGE-----
          fp: F00DF7641634FAF2C004B9D0273CEC26773FA491
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
