---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: influxdb2
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: default
      interval: 1m
  values:
    adminUser:
      bucket: nebula
      existingSecret: influxdb2-auth
      organization: choclab
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      hostname: influx.choclab.net
      ingressClassName: nginx
    persistence:
      storageClass: nfs-client
