---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: "2.14.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
      interval: 1m
  values:
    config:
      query_range:
        parallelise_shardable_queries: false
        split_queries_by_interval: 0
      query_scheduler:
        max_outstanding_requests_per_tenant: 2048
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      enabled: true
      hosts:
      - host: loki.${domain}
        paths:
        - /
    persistence:
      enabled: true
      storageClassName: nfs-client


