---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: promtail
      version: "6.2.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
      interval: 1m
  values:
    config:
      lokiAddress: "https://loki.${domain}/loki/api/v1/push"
