---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-driver
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-driver
        namespace: kube-system
      interval: 1m
  values:
    replicaCount: 3
    nfs:
      server: ${nfsServer}.${domain}
      path: ${nfsPath}
