---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: default
      interval: 1m
  values:
    controller:
      image:
        allowPrivilegeEscalation: false
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
          tcp:
            "8080": 32808
    tcp:
      "8201": "vault/vault-active:8201"

