apiVersion: v1
data:
    password: ENC[AES256_GCM,data:oGUTze44UmKeKOLfPSld6tgRLBX4etDVc6I3N53TdCMQTuud6L99anaXalfBj5IEBw6nE2/xB3k=,iv:9MToQrM29HZQO3gpeNVfWQaoFWAZaX/zFSLKPLTdVd0=,tag:Vd9/N1Qbwlg+nEs+osVRGg==,type:str]
    username: ENC[AES256_GCM,data:Sq03QqXhHtDko4qI,iv:trWsB3DstOYr9gDX74KFFapjKTwWHTv8l4W8lg4k6yg=,tag:mtdrJoJgYHOuuKhrHQIniQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: https-credentials
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-11T18:02:35Z"
    mac: ENC[AES256_GCM,data:yFD2fvQlUikf69jKPxMokT7tqq3b3hP5c8GeKPDofy0WbzC1Psk9fOxx7Fu9FyEXrFzN1hDe5L3bB3+yyAjAuTQyodWfbSoht83ZVbgJwzG5YjawdcHKu8nPRN+/5J42Qi8+7ltS4QaiGuz2cH34v44VZM7/v0rtUTkYXC03pbM=,iv:Y33CYs9S92WqmSItAtUQ4ZUCei0Yywczd1hEMFDaWpc=,tag:fP13hbJucp6P7grzpf5leg==,type:str]
    pgp:
        - created_at: "2024-02-11T18:02:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyC81PBBqFTyARAAnaetn+TbTdoAOq0UebohBZQzyF5Lc10OeorwnFKs/wR4
            FyhdoosrVc0KIebjsm2FmWb9hlAaFNIJJT37E6LFKc0beq7bh4ZRp98VSBisq+E7
            Z3+k6qyN+ikJIrG8zsreil/b26CheQdFxNySRqcGzlC7RGEmfuws8GWu8zCZ5iBN
            i8GRFX24EE/x8FgBUa8i9r9MX+1IgTGuP0fKM28BujVRnGUsCXsFfcLhwiOi+jo9
            ZeNZZtqf8r/Lr7Nf9/ABddR4Jeb/EpKfrCskhJY9V2bepu2iA3hJ/PS41GFNgldv
            Z2qa6LkGkUATXS0XJAaO6vSlrfFqq0QAeFpVLGVTFQ0bL/jxJJsm9iyWrKqphNKN
            h4+EWHxozjBndyXakDhCxEuR08X9Y+EjLrzVrWhiaOsv/RBotj8KWxOiRE/zUrVT
            hQofbU8O1rbGErBd0hmzTEYLdvwy3Too8cmd6IPV4PA+Krt0pc2kkm7nwIEZcY1f
            NSqT573yWmhogGgGYYZPgC4UDYPKrsnVRWjNUFj9LEu00T1pzNU+cvwgIEXxC0eF
            45JytRMhBskgWee19sCU8XTLp6hYT9VeZj8qO+XVZflhYN5NuiGbV2T07QS4GpW3
            ut+csPXGmSuqDQrt6ZTkWe5cv2Cz9d9b376TvKpxG68WQqDQNGKMg66+ayhz25rS
            XgFTC3UXjSJY4nHFMctIKHRL/FqiHJ8mapa3tsP9ztn1VQii2QycN6CDkmTkGHA2
            tZDMwfexo/NsBIzihGNf5z2OWZOMGVWolTZTkVDEweaUA7OwHFxBZSTzg79eKsA=
            =1qP5
            -----END PGP MESSAGE-----
          fp: F00DF7641634FAF2C004B9D0273CEC26773FA491
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
